//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DV402.S2.L1C {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1DV402.S2.L1C.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Inga fler gissningar! Det hemliga talet var {0}..
        /// </summary>
        internal static string Cannot_Guess {
            get {
                return ResourceManager.GetString("Cannot_Guess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Nytt hemligt nummer? [N] avbryter.    .
        /// </summary>
        internal static string Continue_Prompt {
            get {
                return ResourceManager.GetString("Continue_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Första.
        /// </summary>
        internal static string Count_1 {
            get {
                return ResourceManager.GetString("Count_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andra.
        /// </summary>
        internal static string Count_2 {
            get {
                return ResourceManager.GetString("Count_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tredje.
        /// </summary>
        internal static string Count_3 {
            get {
                return ResourceManager.GetString("Count_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjärde.
        /// </summary>
        internal static string Count_4 {
            get {
                return ResourceManager.GetString("Count_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femte.
        /// </summary>
        internal static string Count_5 {
            get {
                return ResourceManager.GetString("Count_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sjätte.
        /// </summary>
        internal static string Count_6 {
            get {
                return ResourceManager.GetString("Count_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sjunde.
        /// </summary>
        internal static string Count_7 {
            get {
                return ResourceManager.GetString("Count_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gissningen: .
        /// </summary>
        internal static string Guess_Number {
            get {
                return ResourceManager.GetString("Guess_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔══════════════════════════════════════╗ 
        ///║ Gissa det hemliga talet mellan 1-100 ║ 
        ///╚══════════════════════════════════════╝ 
        ///.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gissa ett heltal mellan 1-100..
        /// </summary>
        internal static string Help_Prompt {
            get {
                return ResourceManager.GetString("Help_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} är för högt..
        /// </summary>
        internal static string Outcome_High {
            get {
                return ResourceManager.GetString("Outcome_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} är för lågt..
        /// </summary>
        internal static string Outcome_Low {
            get {
                return ResourceManager.GetString("Outcome_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga fler gissningar!.
        /// </summary>
        internal static string Outcome_NoMoreGuesses {
            get {
                return ResourceManager.GetString("Outcome_NoMoreGuesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har redan gissat på talet {0}!.
        /// </summary>
        internal static string Outcome_OldGuess {
            get {
                return ResourceManager.GetString("Outcome_OldGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RÄTT GISSAT! Grattis du klarade det på {0} försöket..
        /// </summary>
        internal static string Outcome_Right {
            get {
                return ResourceManager.GetString("Outcome_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gissa det hemliga talet - nivå C.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett oväntat fel inträffade! Programmet avbryts..
        /// </summary>
        internal static string Unexpected_Exception {
            get {
                return ResourceManager.GetString("Unexpected_Exception", resourceCulture);
            }
        }
    }
}
