//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1._1_Växelpengar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1._1_Växelpengar.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lappar.
        /// </summary>
        internal static string bills {
            get {
                return ResourceManager.GetString("bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontant.
        /// </summary>
        internal static string cash {
            get {
                return ResourceManager.GetString("cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillbaka.
        /// </summary>
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kronor.
        /// </summary>
        internal static string coins {
            get {
                return ResourceManager.GetString("coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange erhållet belopp.
        /// </summary>
        internal static string enter_received {
            get {
                return ResourceManager.GetString("enter_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange totalsumma.
        /// </summary>
        internal static string enter_total {
            get {
                return ResourceManager.GetString("enter_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryck tangent för ny beräkning - ESC avslutar..
        /// </summary>
        internal static string new_calc {
            get {
                return ResourceManager.GetString("new_calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel! &apos;{0}&apos; kan inte tolkas som en giltig summa pengar..
        /// </summary>
        internal static string not_valid {
            get {
                return ResourceManager.GetString("not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVITTO.
        /// </summary>
        internal static string receipt {
            get {
                return ResourceManager.GetString("receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öresavrundning.
        /// </summary>
        internal static string rounding_off_amount {
            get {
                return ResourceManager.GetString("rounding_off_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----------------------------.
        /// </summary>
        internal static string separator {
            get {
                return ResourceManager.GetString("separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Att betala.
        /// </summary>
        internal static string to_pay {
            get {
                return ResourceManager.GetString("to_pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel! &apos;{0}&apos; är ett för litet belopp..
        /// </summary>
        internal static string too_small {
            get {
                return ResourceManager.GetString("too_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totalt.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
    }
}
